# This file is managed by dropfort/dropfort_module_build.
# Modifications to this file will be overwritten by default.

########################################
# Environment detection patterns.
########################################

.feature_detect_template:
  variables:
    DF_ENV_TYPE: feature
  environment:
    name: feature/$CI_COMMIT_REF_NAME
    action: prepare
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'

.dev_detect_template:
  variables:
    DF_ENV_TYPE: dev
  environment:
    name: dev
    action: prepare
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

.qa_detect_template:
  variables:
    DF_ENV_TYPE: qa
  environment:
    name: qa
    action: prepare
  rules:
    - if: '$CI_COMMIT_TAG ~= /^v?\d+\.\d+\.\d+-.+$/'

.prod_detect_template:
  variables:
    DF_ENV_TYPE: prod
  environment:
    name: prod
    action: prepare
  rules:
    - if: '$CI_COMMIT_TAG ~= /^v?\d+\.\d+\.\d+$/'
